model:
  target: pl_modules.ldm_module.LDM
  ckpt_path: LDM_/hsnfmums/checkpoints/last.ckpt
  params:
    in_channels: 16
    out_channels: 16
    rescale_latents: False
    normalize_latents: True

first_stage:
  target: pl_modules.diffusers_vae_module.WeightedSSIMKspaceAutoencoder
  ckpt_path: WeightedSSIMKspaceAutoencoder/8fvbciuk/checkpoints/WeightedSSIMKspaceAutoencoder-epoch=36.ckpt

data:
  target: pl_modules.data_module.LDMLatentDataModule
  params: 
    batch_size: 32
    n_workers: 12
    data_path: /home/atuin/b180dc/b180dc46/WeightedSSIMKspaceAutoencoder/8fvbciuk
    challenge: singlecoil

trainer:
  max_epochs: 1000
  checkpoint:
    top_k: 1
    monitor: val/mse_noise_loss_epoch
    mode: min
               