model:
  target: pl_modules.unet_module.UNet
  ckpt_path: 
  params:
    in_channels: 2
    out_channels: 2
    latent_dim: 16
    n_channels: 128
    num_log_images: 32
    downsample_layers: 3
    with_residuals: True
    norm: True

               


data:
  batch_size: 1
  n_workers: 8
  data_path: /home/janus/iwbi-cip-datasets/shared/fastMRI/knee
  challenge: singlecoil
  transform:
    adapt_pool: True
  mask_func:
    type: equispaced_fraction
    center_fractions: [0.04]
    accelerations: [8]


trainer:
  max_epochs: 100
  checkpoint:
    top_k: 1
    monitor: val/ssim_epoch
    mode: max