name: kdiff
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.8.90
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.8.90
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.4.1
  - pip=25.0.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.11
  - python_abi=3.10
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.2
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.5.0
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - accelerate==1.5.2
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - albucore==0.0.23
    - albumentations==2.0.5
    - altair==5.5.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==24.3.0
    - blinker==1.9.0
    - cachetools==5.5.2
    - certifi==2024.12.14
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.2
    - debugpy==1.8.12
    - decorator==5.1.1
    - diffusers==0.32.2
    - einops==0.3.0
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastmri==0.3.0
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - future==1.0.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - grpcio==1.69.0
    - h5py==3.12.1
    - huggingface-hub==0.27.1
    - hydra-core==1.3.2
    - imageio==2.36.1
    - imageio-ffmpeg==0.6.0
    - importlib-metadata==8.5.0
    - iniconfig==2.0.0
    - ipykernel==6.29.5
    - ipython==8.31.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - lazy-loader==0.4
    - lightning-utilities==0.11.9
    - markdown==3.7
    - matplotlib-inline==0.1.7
    - more-itertools==10.6.0
    - multidict==6.2.0
    - narwhals==1.31.0
    - nest-asyncio==1.6.0
    - numpy==2.2.1
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - omegaconf==2.3.0
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pexpect==4.9.0
    - pillow==11.1.0
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - prompt-toolkit==3.0.50
    - propcache==0.2.1
    - protobuf==5.29.3
    - psutil==6.1.1
    - ptyprocess==0.7.0
    - pudb==2024.1.3
    - pure-eval==0.2.3
    - pyarrow==19.0.1
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydeck==0.9.1
    - pygments==2.19.1
    - pytest==8.3.5
    - python-dateutil==2.9.0.post0
    - pytorch-ignite==0.5.1
    - pytorch-lightning==2.5.0.post0
    - pytz==2024.2
    - pyzmq==26.2.0
    - referencing==0.36.2
    - regex==2024.11.6
    - rpds-py==0.23.1
    - runstats==2.0.0
    - safetensors==0.5.2
    - scikit-image==0.25.0
    - scipy==1.15.1
    - simsimd==6.2.1
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - streamlit==1.43.2
    - stringzilla==3.12.3
    - sympy==1.13.1
    - taming-transformers==0.0.1
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - test-tube==0.7.5
    - tifffile==2025.1.10
    - tokenizers==0.21.1
    - toml==0.10.2
    - tomli==2.2.1
    - torch==2.6.0
    - torchmetrics==1.6.2
    - torchvision==0.21.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==3.2.0
    - tzdata==2024.2
    - urwid==2.6.16
    - urwid-readline==0.15.1
    - watchdog==6.0.0
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - yarl==1.18.3
    - zipp==3.21.0
