model:
  target: pl_modules.diffusers_vae_module.KspaceAutoencoder
  ckpt_path: KspaceAutoencoder/1477y5so/checkpoints/KspaceAutoencoder-epoch=32.ckpt

data:
  batch_size: 1
  n_workers: 8
  data_path: /home/janus/iwbi-cip-datasets/shared/fastMRI/knee
  challenge: singlecoil
  transform:
    adapt_pool: True
  mask_func:
    type: equispaced
    center_fractions: [0.08]
    accelerations: [4]
