model:
  target: pl_modules.diffusers_vae_module.WeightedSSIMKspaceAutoencoder
  ckpt_path: WeightedSSIMKspaceAutoencoder/8fvbciuk/checkpoints/WeightedSSIMKspaceAutoencoder-epoch=36.ckpt

data:
  batch_size: 1
  n_workers: 8
  data_path: /home/janus/iwbi-cip-datasets/shared/fastMRI/knee
  challenge: singlecoil
  transform:
    adapt_pool: True
  mask_func:
    type: equispaced_fraction
    center_fractions: [0.04]
    accelerations: [8]
