model:
  target: pl_modules.diffusers_vae_module.KspaceAutoencoderKL
  params:
    in_channels: 2
    out_channels: 2
    latent_dim: 16
    n_mult: [1,2,2,4]
    n_channels: 128   
    num_log_images: 32
    sample_posterior: False   
               


data:
  batch_size: 6
  n_workers: 4
  data_path: /home/janus/iwbi-cip-datasets/shared/fastMRI/knee
  challenge: singlecoil
  transform:
    adapt_pool: True
  mask_func:
    type: equispaced_fraction
    center_fractions: [0.04]
    accelerations: [8]


trainer:
  max_epochs: 100
  checkpoint:
    top_k: 2
    monitor: val/ssim_epoch
    mode: max